---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: applications-dr
  annotations:
    argocd.argoproj.io/sync-wave: "300"
  labels:
    gitops.tier.layer: gitops
spec:
  destination:
    namespace: openshift-gitops
    server: https://c111-e.us-east.containers.cloud.ibm.com:31784
  project: default
  source: 
    repoURL: https://github.com/iiab-mw-gitops/prod-cluster-gitops-apps.git
    path: ace
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
