--- 
apiVersion: route.openshift.io/v1
kind: Route
metadata: 
  name: el-ace-integration-server
spec: 
  port: 
    targetPort: http-listener
    #tls: 
    #  termination: passthrough
  to: 
    kind: Service
    name: el-ace-integration-server
  wildcardPolicy: None
