apiVersion: appconnect.ibm.com/v1beta1
kind: IntegrationServer
metadata:
  name: hello-app-rest
spec:
  designerFlowsOperationMode: disabled
  license:
    accept: true
    license: L-APEH-C49KZH
    use: CloudPakForIntegrationNonProduction
  replicas: 1
  router:
    timeout: 120s
  service:
    endpointType: http
  useCommonServices: true
  version: 12.0.2.0-r1
  adminServerSecure: true
  pod:
    containers:
      runtime:
        image: image-registry.openshift-image-registry.svc:5000/ci/hello-app-rest:745b1b6efd8a14f48c5730589edcf6e54580292e
        imagePullPolicy: Always
  configurations:
    - create-customer-serverconf.yaml
